window.characters = [
	{
		id:          "abdul-alhazred",
		name:        "Abdul Alhazred",
		description: "The Mad Arab, a sorcerer and poet from Yemen who authored the dreaded Necronomicon after years of wandering the Empty Quarter and the ruins of Babylon, driven half-insane by what he witnessed.",
		publication: "The Wolverine",
		date:        "Nov. 1921",
		sortDate:    192111,
		story:       "The Nameless City",
		author:      "H.P. Lovecraft",
		alignment:   "Evil",
		type:        "Human",
		environment: "Urban",
	},
	{
		id:          "azathoth",
		name:        "Azathoth",
		description: "The Blind Idiot God, a mindless nuclear chaos seated at the center of ultimate confusion, piped to by a thin monotonous flute as lesser gods dance around it at the court of chaos.",
		publication: "Weird Tales",
		date:        "Aug. 1931",
		sortDate:    193108,
		story:       "The Whisperer in Darkness",
		author:      "H.P. Lovecraft",
		alignment:   "Cosmic",
		type:        "Outer God",
		environment: "Cosmic",
	},
	{
		id:          "charles-dexter-ward",
		name:        "Charles Dexter Ward",
		description: "A Providence antiquarian obsessed with his ancestor Joseph Curwen, who gradually unearthed forbidden techniques of resurrection and essential salts — with catastrophic consequences for his own identity.",
		publication: "Weird Tales",
		date:        "May 1941",
		sortDate:    194105,
		story:       "The Case of Charles Dexter Ward",
		author:      "H.P. Lovecraft",
		alignment:   "Evil",
		type:        "Human",
		environment: "Urban",
	},
	{
		id:          "cthulhu",
		name:        "Cthulhu",
		description: "The Great Old One who lies dead but dreaming in the sunken city of R'lyeh, his psychic influence haunting sensitive minds worldwide until the stars are right and he rises again.",
		publication: "Weird Tales",
		date:        "Feb. 1928",
		sortDate:    192802,
		story:       "The Call of Cthulhu",
		author:      "H.P. Lovecraft",
		alignment:   "Evil",
		type:        "Great Old One",
		environment: "Ocean",
	},
	{
		id:          "deep-one",
		name:        "Deep One",
		description: "An amphibious humanoid race that dwells in the ocean depths, interbreeding with isolated coastal communities and serving their masters Dagon and Cthulhu from the reef beneath Innsmouth.",
		publication: "Visionary Publishing",
		date:        "1936",
		sortDate:    193600,
		story:       "The Shadow over Innsmouth",
		author:      "H.P. Lovecraft",
		alignment:   "Evil",
		type:        "Ancient Race",
		environment: "Ocean",
	},
	{
		id:          "elder-thing",
		name:        "Elder Thing",
		description: "An ancient barrel-shaped creature who colonized Earth billions of years ago, creating all life including humanity as a byproduct, only to fall before the shoggoths they themselves engineered.",
		publication: "Astounding Stories",
		date:        "Feb. 1936",
		sortDate:    193602,
		story:       "At the Mountains of Madness",
		author:      "H.P. Lovecraft",
		alignment:   "Neutral",
		type:        "Ancient Race",
		environment: "Arctic",
	},
	{
		id:          "hastur",
		name:        "Hastur",
		description: "The Unspeakable One, a malevolent entity associated with the Yellow Sign and the dread play The King in Yellow, whose true nature and form remain deliberately obscure and maddening.",
		publication: "Weird Tales",
		date:        "Aug. 1931",
		sortDate:    193108,
		story:       "The Whisperer in Darkness",
		author:      "H.P. Lovecraft",
		alignment:   "Evil",
		type:        "Outer God",
		environment: "Cosmic",
	},
	{
		id:          "herbert-west",
		name:        "Herbert West",
		description: "A brilliant and coldly amoral physician whose obsession with conquering death through chemical reanimation produced only shambling, murderous horrors that ultimately turned on their creator.",
		publication: "Home Brew",
		date:        "Feb. 1922",
		sortDate:    192202,
		story:       "Herbert West—Reanimator",
		author:      "H.P. Lovecraft",
		alignment:   "Evil",
		type:        "Human",
		environment: "Urban",
	},
	{
		id:          "inspector-legrasse",
		name:        "Inspector Legrasse",
		description: "A New Orleans police inspector who raided a Louisiana swamp cult worshipping an unknown idol, and later brought the statuette to a folklore conference — inadvertently uncovering the global Cthulhu cult.",
		publication: "Weird Tales",
		date:        "Feb. 1928",
		sortDate:    192802,
		story:       "The Call of Cthulhu",
		author:      "H.P. Lovecraft",
		alignment:   "Good",
		type:        "Human",
		environment: "Urban",
	},
	{
		id:          "king-in-yellow",
		name:        "King in Yellow",
		description: "A masked cosmic entity whose identity is concealed even from itself, associated with the Yellow Sign and the mind-destroying play of the same name that drives all who read it to madness.",
		publication: "Weird Tales",
		date:        "Aug. 1931",
		sortDate:    193108,
		story:       "The Whisperer in Darkness",
		author:      "H.P. Lovecraft",
		alignment:   "Evil",
		type:        "Outer God",
		environment: "Cosmic",
	},
	{
		id:          "nyarlathotep",
		name:        "Nyarlathotep",
		description: "The Crawling Chaos — shapeshifting soul and messenger of the Outer Gods who, unlike his brethren, takes an active and malicious delight in spreading madness and destruction among humanity.",
		publication: "The United Amateur",
		date:        "Nov. 1920",
		sortDate:    192011,
		story:       "Nyarlathotep",
		author:      "H.P. Lovecraft",
		alignment:   "Evil",
		type:        "Outer God",
		environment: "Cosmic",
	},
	{
		id:          "randolph-carter",
		name:        "Randolph Carter",
		description: "A dreamer and mystic from Boston who can enter the Dreamlands at will, where he seeks the fabled Sunset City and encounters gods, ghouls, and the Ultimate Gate beyond the boundaries of space and time.",
		publication: "The Vagrant",
		date:        "May 1920",
		sortDate:    192005,
		story:       "The Statement of Randolph Carter",
		author:      "H.P. Lovecraft",
		alignment:   "Good",
		type:        "Human",
		environment: "Dreamlands",
	},
	{
		id:          "rhan-tegoth",
		name:        "Rhan-Tegoth",
		description: "A bloated, tentacled Great Old One who once ruled arctic Earth before going into a centuries-long torpor, requiring blood sacrifices to revive — displayed in a London wax museum as its unwitting caretaker plots his awakening.",
		publication: "Weird Tales",
		date:        "Jul. 1933",
		sortDate:    193307,
		story:       "The Horror in the Museum",
		author:      "H.P. Lovecraft & Hazel Heald",
		alignment:   "Evil",
		type:        "Great Old One",
		environment: "Arctic",
	},
	{
		id:          "shoggoth",
		name:        "Shoggoth",
		description: "A massive, amorphous mass of iridescent black protoplasm with hundreds of temporary eyes and pseudopods, created by the Elder Things as a servile beast of burden before turning on their makers.",
		publication: "Astounding Stories",
		date:        "Feb. 1936",
		sortDate:    193602,
		story:       "At the Mountains of Madness",
		author:      "H.P. Lovecraft",
		alignment:   "Evil",
		type:        "Monster",
		environment: "Arctic",
	},
	{
		id:          "shub-niggurath",
		name:        "Shub-Niggurath",
		description: "The Black Goat of the Woods with a Thousand Young — a perverse fertility deity of immense power whose goat-like form spawns the Dark Young that lumber through forests and desecrate the countryside.",
		publication: "Weird Tales",
		date:        "Nov. 1928",
		sortDate:    192811,
		story:       "The Last Test",
		author:      "H.P. Lovecraft & Adolphe de Castro",
		alignment:   "Cosmic",
		type:        "Outer God",
		environment: "Rural",
	},
	{
		id:          "sleeper-cultist",
		name:        "Sleeper Cultist",
		description: "A devoted worshipper of the Great Old Ones who keeps the faith alive in isolated cells, performing rituals in hidden underground spaces and awaiting the day the stars align for their masters' return.",
		publication: "Weird Tales",
		date:        "Aug. 1931",
		sortDate:    193108,
		story:       "The Whisperer in Darkness",
		author:      "H.P. Lovecraft",
		alignment:   "Evil",
		type:        "Cultist",
		environment: "Underground",
	},
	{
		id:          "star-spawn",
		name:        "Star-Spawn",
		description: "Cthulhu's own kindred who accompanied him from the stars and built R'lyeh — great winged beings that warred with the Elder Things before sinking with their city beneath the Pacific Ocean.",
		publication: "Weird Tales",
		date:        "Feb. 1928",
		sortDate:    192802,
		story:       "The Call of Cthulhu",
		author:      "H.P. Lovecraft",
		alignment:   "Evil",
		type:        "Ancient Race",
		environment: "Ocean",
	},
	{
		id:          "star-vampire",
		name:        "Star Vampire",
		description: "An invisible predatory entity from deep space that becomes briefly visible when engorged with blood — a bloated, crimson, tentacled horror that laughs as it feeds before vanishing back into the void.",
		publication: "Weird Tales",
		date:        "Sep. 1935",
		sortDate:    193509,
		story:       "The Shambler from the Stars",
		author:      "Robert Bloch",
		alignment:   "Evil",
		type:        "Monster",
		environment: "Cosmic",
	},
	{
		id:          "tsathaggua",
		name:        "Tsathoggua",
		description: "A formless, toad-like entity of immense antiquity who came to Earth from Saturn and now slumbers in caverns beneath N'kai, demanding little worship but consuming any who venture into his domain.",
		publication: "Weird Tales",
		date:        "Aug. 1931",
		sortDate:    193108,
		story:       "The Whisperer in Darkness",
		author:      "H.P. Lovecraft",
		alignment:   "Evil",
		type:        "Great Old One",
		environment: "Underground",
	},
	{
		id:          "wilbur-whateley",
		name:        "Wilbur Whateley",
		description: "A half-human, half-cosmic hybrid born in the Dunwich hills, who grew at an impossible rate and sought to obtain the complete Necronomicon to summon his invisible twin and open the gates for Yog-Sothoth.",
		publication: "Weird Tales",
		date:        "Apr. 1929",
		sortDate:    192904,
		story:       "The Dunwich Horror",
		author:      "H.P. Lovecraft",
		alignment:   "Evil",
		type:        "Hybrid",
		environment: "Rural",
	},
	{
		id:          "yig-father-of-serpents",
		name:        "Yig",
		description: "The Father of Serpents, a Great Old One worshipped across the American plains whose vengeance falls on any who harm his serpent children — inflicting transformation, madness, or death on transgressors.",
		publication: "Weird Tales",
		date:        "Nov. 1929",
		sortDate:    192911,
		story:       "The Curse of Yig",
		author:      "H.P. Lovecraft & Zealia Bishop",
		alignment:   "Neutral",
		type:        "Great Old One",
		environment: "Rural",
	},
	{
		id:          "yog-sothoth",
		name:        "Yog-Sothoth",
		description: "The All-in-One and One-in-All — an Outer God who is coterminous with all time and space, manifesting as a congeries of iridescent spheres and serving as the gate and the key to all dimensions.",
		publication: "Weird Tales",
		date:        "Apr. 1929",
		sortDate:    192904,
		story:       "The Dunwich Horror",
		author:      "H.P. Lovecraft",
		alignment:   "Cosmic",
		type:        "Outer God",
		environment: "Cosmic",
	},
];
